#syntax=docker/dockerfile:1.2
#---------------------------------------------------------------------------------------------------
# build
# Descriptiuon: 
#---------------------------------------------------------------------------------------------------

# declare arguments with defaults
# Meta args
ARG TARGET_NAME="unspecified"
ARG GIT_COMMIT="unspecified"
ARG MAINTAINERS="https://github.com/nixzee"

#---------------------------------------------------------------------------------------------------
# Section: Build
# Description: Copies the project in and runs the Makefile
#---------------------------------------------------------------------------------------------------
# FROM arm-none-eabi-gcc AS build
# TODO: Should really pass in the name of the toolchain.
# FROM gcc-arm-none-eabi-10-2020-q4-major:latest AS build 
FROM test/gcc-arm-none-eabi-10-2020-q4-major:1.0.0 AS build
LABEL stage=

# Copy over the project
COPY ./src /workspace/src
RUN ls -al /workspace/src

WORKDIR /workspace/src
# Setup a temp for artifacts we may want
# cache mount does some weird stuff
RUN mkdir tmp

# Make the project
# https://hub.docker.com/r/docker/dockerfile
# The packages are stored outside of the docker layer, in a volume cache in the host.
# TODO: Fix this...was copied from my STM32 project
RUN --mount=id=make,type=cache,target=/workspace/src/build \
    cmake .. \
    make clean all \
    && ls -al build/ \
    && cp build/*.elf tmp/ \
    && cp build/*.hex tmp/ \
    && cp build/*.bin tmp/

#---------------------------------------------------------------------------------------------------
# Section: Artifact
# Description: Get the elf file
#---------------------------------------------------------------------------------------------------
FROM scratch AS artifact
LABEL stage=artifact

# Declare args in scope
ARG TARGET_NAME
ENV TARGET_NAME=${TARGET_NAME}

# Copy
COPY --from=build /workspace/${TARGET_NAME}/tmp/${TARGET_NAME}.elf .
COPY --from=build /workspace/${TARGET_NAME}/tmp/${TARGET_NAME}.hex .
COPY --from=build /workspace/${TARGET_NAME}/tmp/${TARGET_NAME}.bin .
